version: 0.2

phases:
  install:
    commands:
      - sudo apt update
      - sudo apt install openjdk-11-jdk -y
      - sudo apt install maven -y
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'